---

- include: package.yml

- include: config.yml

- include: service.yml


#  create_resources('nginx::resource::upstream', $nginx_upstreams)
#  create_resources('nginx::resource::vhost', $nginx_vhosts, $nginx_vhosts_defaults)
#  create_resources('nginx::resource::location', $nginx_locations)
#  create_resources('nginx::resource::mailhost', $nginx_mailhosts)
#  create_resources('nginx::resource::map', $string_mappings)
#  create_resources('nginx::resource::geo', $geo_mappings)

