---

- name: Validate nginx config
  shell: /etc/init.d/nginx configtest
  when: nginx_configtest_enable and ansible_os_family|lower == 'debian'

- name: Restart nginx
  service: name={{ nginx_service_name }} state=restarted

- name: Update nginx apt cache
  apt: update_cache=yes
