---

- set_fact: 
      _vhost_fragments_dir: "{{ nginx_conf_fragments_dir }}/conf.sites.d"

- name: Validate vhost variable for location config is defined
  fail: msg="Cannot create a location reference without attaching to a virtual host"
  when: item.vhost is not defined
  with_items: "{{ nginx_location }}"

- name: Validate nginx_location params
  fail: msg="Cannot create a location reference without a www_root, proxy, location_alias, fastcgi, uwsgi, stub_status, internal or location_custom_cfg defined"
  when: (item.www_root is not defined) and (item.proxy_pass is not defined) and
            (item.location_alias is not defined) and (item.stub_status is not defined)
                (item.fastcgi_pass is not defined) and (item.uwsgi_pass is not defined)
                    (item.custom_cfg is not defined) and (item.internal is not defined)
  with_items: "{{ nginx_location }}"

- name: Validate www_root and proxy variables are not both defined
  fail: msg="Cannot define both directory and proxy in a virtual host"
  when: (item.www_root is defined and item.www_root) and (item.proxy_pass is defined and item.proxy_pass)
  with_items: "{{ nginx_location }}"

- name: Validate vhost name does not contain invalid characters
  fail: msg="Cannot have whitespace, '/' or '_' characters in vhost name"
  when: item.vhost|search(' |/|_')
  with_items: "{{ nginx_location }}"

# Consider moving fastcgi and uwsgi_params files tasks to config.yml
- name: Create nginx fastcgi params conf file
  template: 
    src:    vhost/fastcgi_params.j2 
    dest:   "{{ nginx_fastcgi_params_file }}"
    owner:  root 
    group:  root
    mode:   0644
  when: item.fastcgi_pass|default(false)
  with_items: "{{ nginx_location }}"

- name: Create nginx uwsgi params conf file
  template: 
    src:    vhost/uwsgi_params.j2
    dest:   "{{ nginx_uwsgi_params_file }}"
    owner:  root
    group:  root
    mode:   0644
  when: item.uwsgi_pass|default(false)
  with_items: "{{ nginx_location }}"

- name: Create nginx location config for non-ssl vhost
  template:
    src:    vhost/location.j2 
    dest:   "{{ _vhost_fragments_dir }}/{{ item.vhost }}/410-nonssl-{{ item.location|regex_replace(' |/', '_') }}.location" 
    owner:  root 
    group:  root 
    mode:   0644
  when: not item.ssl|default(false) 
  with_items: "{{ nginx_location }}"

- name: Create nginx location config for ssl vhost
  template: 
    src:    vhost/location.j2
    dest:   "{{ _vhost_fragments_dir }}/{{ item.vhost }}/810-ssl-{{ item.location|regex_replace(' |/', '_') }}.location"
    owner:  root
    group:  root
    mode:   0644
  when: item.ssl|default(false)
  with_items: "{{ nginx_location }}"

## Configure default location '/' for each vhost with use_default_location attribute enabled
- name: Create nginx default location config for non-ssl vhost
  template: 
    src:    vhost/location.j2
    dest:   "{{ _vhost_fragments_dir }}/{{ item.vhost }}/400-nonssl-default.location"
    owner:  root
    group:  root
    mode:   0644
  when: item.use_default_location and not item.ssl|default(false)
  with_items: "{{ nginx_vhost }}"

- name: Create nginx default location config for ssl vhost
  template: 
    src:    vhost/location.j2 
    dest:   "{{ _vhost_fragments_dir }}/{{ item.vhost }}/800-ssl-default.location"
    owner:  root
    group:  root
    mode:   0644
  when: item.use_default_location and item.ssl|default(false)
  with_items: "{{ nginx_vhost }}"
