---
- name: Validate nginx_map_string
  fail: msg="Invalid map string!! Cannot be an empty string"
  when: nginx_map_string == '' and config_nginx_map

- name: Create nginx map config
  template: src=conf.d/map.j2 dest={{ nginx_conf_dir }}/conf.d/{{ nginx_map_name }}-map.conf owner=root group=root mode=0644 state=present
  when: config_nginx_map
  notify: Restart nginx
