---
- name: Validate nginx_map_string
  fail: msg="Invalid map string!! Cannot be an empty string"
  when: item.string == ''
  with_items: "{{ nginx_map }}"

- name: Create nginx map config
  template: 
    src:    conf.d/map.j2 
    dest:   "{{ nginx_conf_dir }}/conf.d/{{ item.name }}-map.conf" 
    owner:  root
    group:  root
    mode:   0644
  with_items: "{{ nginx_map }}"
  notify: Restart nginx
