---
- set_fact:
    nginx_yum_repo_os_distro: centos
  when: ansible_distribution|lower == 'centos'

- name: Set nginx yum repo baseurl | stable version
  set_fact:
    nginx_yum_repo_baseurl: "{{ nginx_mainline_yum_repo_baseurl }}"
  when: nginx_package_source == 'nginx-mainline'

- name: Add nginx yum repository config
  yum_repository:
    name: nginx
    description: "Nginx Repository"
    baseurl: "{{ nginx_yum_repo_baseurl }}"
    gpgkey: "http://nginx.org/keys/nginx_signing.key"
    gpgcheck: yes
    enabled:  yes

- name: Set nginx package name if version is set
  set_fact:
    _nginx_package: "{{ nginx_package_name }}-{{ nginx_version }}"
  when: nginx_version != '*'

- name: Install nginx package
  yum:
    name: "{{ _nginx_package|default(nginx_package_name) }}"
    update_cache: yes
    state: present
